class int(object):
    def __add__(self, *args, **kwargs): ...
    def __and__(self, *args, **kwargs): ...
    def __bool__(self, *args, **kwargs): ...
    def __eq__(self, *args, **kwargs): ...
    def __float__(self, *args, **kwargs): ...
    def __ge__(self, *args, **kwargs): ...
    def __gt__(self, *args, **kwargs): ...
    def __int__(self, *args, **kwargs): ...
    def __le__(self, *args, **kwargs): ...
    def __lt__(self, *args, **kwargs): ...
    def __ne__(self, *args, **kwargs): ...
    def __pow__(self, *args, **kwargs): ...

    # And many more ...

foo: float = 1.00
